# Generated by Django 4.1.7 on 2023-03-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('categories', models.ManyToManyField(to='category.category')),
            ],
            options={
                'verbose_name': 'Авторы',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('time_create', models.DateTimeField(auto_now=True)),
                ('time_update', models.DateTimeField(auto_now_add=True)),
                ('book_name', models.CharField(max_length=255, null=True)),
                ('link', models.JSONField(default=dict, null=True)),
                ('authors', models.ManyToManyField(to='mathsources.author')),
                ('categories', models.ManyToManyField(to='category.category')),
            ],
            options={
                'verbose_name': 'Книги',
                'verbose_name_plural': 'Книги',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
