# Generated by Django 4.1.7 on 2023-02-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathsources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=None, upload_to='images/categories'),
        ),
    ]
