# Generated by Django 4.1.7 on 2023-02-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathsources', '0006_alter_category_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
    ]
