# Generated by Django 4.1.7 on 2023-02-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathsources', '0008_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='topic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
