# Generated by Django 4.1.7 on 2023-02-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathsources', '0009_category_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='book_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
