# Generated by Django 4.1.7 on 2023-02-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathsources', '0010_links_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='links',
        ),
        migrations.AlterField(
            model_name='links',
            name='book_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mathsources.book'),
        ),
    ]
