# Generated by Django 4.1.7 on 2023-02-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathsources', '0011_remove_book_links_alter_links_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
