# Generated by Django 4.1.7 on 2023-03-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('link', models.URLField()),
                ('img', models.ImageField(upload_to='images/courses/')),
                ('categories', models.ManyToManyField(to='category.category')),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курсы',
                'ordering': ['title', 'id'],
            },
        ),
    ]
